name: hello-fittrack
on: # workflow_dispatch = bouton "Run workflow" pour la démo live
  pull_request:
    branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: build
        run: echo "build OK"
         

  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "test OK"
         
