name: hello-fittrack
on: # workflow_dispatch = bouton "Run workflow" pour la démo live
  pull_request:
    branches:
          - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: build
        run: echo "build OK"
         
  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "test OK"
         
